/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blo: typeof import('./components/blo.vue')['default']
    ColorSwitcher: typeof import('./components/ColorSwitcher.vue')['default']
    Left: typeof import('./components/NavigationPanel/Left.vue')['default']
    Mobile: typeof import('./components/NavigationPanel/Mobile.vue')['default']
    MostPopularShowsList: typeof import('./components/MostPopularShowsList.vue')['default']
    PopularShowsBannerList: typeof import('./components/PopularShowsBannerList.vue')['default']
    Right: typeof import('./components/NavigationPanel/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ShowBanner: typeof import('./components/ShowBanner.vue')['default']
    ShowBannerSkeleton: typeof import('./components/ShowBannerSkeleton.vue')['default']
    ShowCard: typeof import('./components/ShowCard.vue')['default']
  }
}
